export const defaultPermissions = [
  {
    name: 'create:User',
    slug: 'create_user',
    entity: 'User',
    action: 'create',
    description: 'Can create users',
  },
  {
    name: 'view:User',
    slug: 'view_user',
    entity: 'User',
    action: 'view',
    description: 'Can view users',
  },
  {
    name: 'update:User',
    slug: 'update_user',
    entity: 'User',
    action: 'update',
    description: 'Can update users',
  },
  {
    name: 'delete:User',
    slug: 'delete_user',
    entity: 'User',
    action: 'delete',
    description: 'Can delete users',
  },
  {
    name: 'create:Project',
    slug: 'create_project',
    entity: 'Project',
    action: 'create',
    description: 'Can create projects',
  },
  {
    name: 'view:Project',
    slug: 'view_project',
    entity: 'Project',
    action: 'view',
    description: 'Can view projects',
  },
  {
    name: 'update:Project',
    slug: 'update_project',
    entity: 'Project',
    action: 'update',
    description: 'Can update projects',
  },
  {
    name: 'delete:Project',
    slug: 'delete_project',
    entity: 'Project',
    action: 'delete',
    description: 'Can delete projects',
  },
  {
    name: 'create:Client',
    slug: 'create_client',
    entity: 'Client',
    action: 'create',
    description: 'Can create clients',
  },
  {
    name: 'view:Client',
    slug: 'view_client',
    entity: 'Client',
    action: 'view',
    description: 'Can view clients',
  },
  {
    name: 'update:Client',
    slug: 'update_client',
    entity: 'Client',
    action: 'update',
    description: 'Can update clients',
  },
  {
    name: 'delete:Client',
    slug: 'delete_client',
    entity: 'Client',
    action: 'delete',
    description: 'Can delete clients',
  },
  {
    name: 'view:OwnActivity',
    slug: 'view_own_activity',
    entity: 'Activity',
    action: 'view',
    description: 'Can view own activity logs',
  },
  {
    name: 'view:Permission',
    slug: 'view_permission',
    entity: 'Permission',
    action: 'view',
    description: 'Can view permissions',
  },
  {
    name: 'view:Role',
    slug: 'view_role',
    entity: 'Role',
    action: 'view',
    description: 'Can view roles',
  },
  {
    name: 'create:Role',
    slug: 'create_role',
    entity: 'Role',
    action: 'create',
    description: 'Can create roles',
  },
  {
    name: 'update:Role',
    slug: 'update_role',
    entity: 'Role',
    action: 'update',
    description: 'Can update roles',
  },
  {
    name: 'delete:Role',
    slug: 'delete_role',
    entity: 'Role',
    action: 'delete',
    description: 'Can delete roles',
  },
];
